Repository hmcts/em-annotation-api, pull requests merged in 2019-10, with the labels that each got.

#50 Added in disableLegacyDeployment()
  Jenkinsfile_CNP
  charts/em-anno/values.aat.template.yaml
  charts/em-anno/values.preview.template.yaml
  dependency-check-suppressions.xml
Labels: ns:em-anno-pr-50

#51 Updated disableLegacyDeploymentOnAAT()
  Jenkinsfile_CNP
Labels: ns:em-anno-pr-51

#71 changing the appinsights var in bootstrap for flux.
  src/main/resources/bootstrap.yaml
Labels: ns:em-anno-pr-71

#74 Suppressed vulnerability
  dependency-check-suppressions.xml
Labels: ns:em-anno-pr-74

#78 gradle upgrade
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: ns:em-anno-pr-78

#85 Removed alias related lines
  charts/em-anno/Chart.yaml
  charts/em-anno/requirements.yaml
  charts/em-anno/values.aat.template.yaml
  charts/em-anno/values.preview.template.yaml
  charts/em-anno/values.yaml
Labels: ns:em-anno-pr-85

#89 reduce error response verbosity to meet ITHC requirements
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java
Labels: ns:em-anno-pr-89
