Repository hmcts/em-annotation-api, pull requests merged in 2019-09, with the labels that each got.

#23 basic SIDAM pact for backend service
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  build.gradle
  lib/AI-Agent.xml
  lib/applicationinsights-agent-2.3.1.jar
  pacts/annotation_api-idam_api.json
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java
  src/contractTest/java/uk/gov/hmcts/reform/em/annotation/IdamConsumerTest.java
Labels: ns:em-anno-pr-23

#25 Update Java image
  Dockerfile
  build.gradle
  docker-compose-dependencies.yml
  lib/AI-Agent.xml
  web.config
Labels: ns:em-anno-pr-25

#26 Fix deprecation issues and use component for vault
  charts/em-anno/Chart.yaml
  infrastructure/main.tf
  infrastructure/output.tf
Labels: ns:em-anno-pr-26

#27 Reverted the vault key changes
  infrastructure/main.tf
Labels: ns:em-anno-pr-27

#28 Replaced the vault_uri with key_vault_id
  infrastructure/main.tf
Labels: ns:em-anno-pr-28

#29 Updated the vault name attribute for postgres details
  infrastructure/main.tf
Labels: ns:em-anno-pr-29

#31 EM-2110: Rename local_key_vault to key_vault
  infrastructure/main.tf
Labels: ns:em-anno-pr-31
