Repository hmcts/em-annotation-api, pull requests merged in 2020-12, with the labels that each got.

#275 EM-3259 - Anno API : Add retry logic for failing functional test cases
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/MetadataScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/TagScenarios.java
Labels: ns:em, prd:em, rel:em-anno-pr-275

#279 EM-3279 - Anno API - Suppress nightly jobs dependency vulnerability e…
  dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-279

#280 Resolved vulnerability
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-280

#290 Resolved vulnerabilities
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-290
