Repository hmcts/em-annotation-api, pull requests merged in 2020-11, with the labels that each got.

#243 Updated spring boot and java chart version
  build.gradle
  charts/em-anno/Chart.yaml
  charts/em-anno/requirements.yaml
  charts/em-anno/values.yaml
  dependency-check-suppressions.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TagResourceIntTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-243

#261 Updated cnp-module-key-vault branch
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-anno-pr-261

#262 Updated terraform version
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-anno-pr-262

#259 EM-3207 Implemented
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/MetadataScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/TagScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java
Labels: ns:em, prd:em, rel:em-anno-pr-259

#263 Em 3235 - Investigate anno api failing nightly build jobs
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-263

#268 EM-3240- Anno API : Suppress nightly build security issues
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-268

#269 Updated azurerm version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-anno-pr-269

#270 Removed mi value for env tf files
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
Labels: ns:em, prd:em, rel:em-anno-pr-270

#272 EM-3255- Anno API : Suppress nightly build security issues
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-272

#274 Updated em-test-helper version
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-274
