Repository hmcts/em-annotation-api, pull requests merged in 2021-01, with the labels that each got.

#300 EM-3324 - EM-Anno api: suppress security scan error
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-300

#301 EM-3325 - EM-Anno api: suppress security scan error
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-301

#315 Em 3361 resolved vulnerability
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-315

#321 EM-3426 - EM-Anno api: Upgrade serenity version
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-321
