Repository hmcts/em-annotation-api, pull requests merged in 2021-08, with the labels that each got.

#543 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-543

#545 Resolved CVE
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-545

#558 upgrade gradle version
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:em, prd:em, rel:em-anno-pr-558
