Repository hmcts/em-annotation-api, pull requests merged in 2021-09, with the labels that each got.

#563 EM-4026-AnnotationsApi-SecurityScan-fix
  audit.json
  security.sh
Labels: ns:em, prd:em, rel:em-anno-pr-563

#564 EM-4024: fix terraform provider issue
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-anno-pr-564

#574 EM-4044: fix checkstyle type error
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListener.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtils.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SpringSecurityAuditorAware.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/PersistentAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Rectangle.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/CommentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationSetServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/MetadataServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/AnnotationMapper.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/BookmarkMapper.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/EntityMapper.java
Labels: ns:em, prd:em, rel:em-anno-pr-574

#575 EM-4044: fix checkstyle type error v2
  src/main/java/uk/gov/hmcts/reform/em/annotation/authchecker/EmAuthCheckerUserDetailsService.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/authchecker/EmServiceAndUserDetails.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AsyncEntityAuditEventWriter.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/AuditEventConverter.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditAction.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Annotation.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AnnotationSet.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/TagId.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/mapper/EntityMapper.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/util/StringUtilities.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TestUtil.java
Labels: ns:em, prd:em, rel:em-anno-pr-575

#576 EM-4044: fix sonar exclusion
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-576

#577 EM-3982: Syncronise Demo/PerfTest/ITHC branches with master
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-anno-pr-577

#578 EM-4044: fix checkstyle type error v4
  src/main/java/uk/gov/hmcts/reform/em/annotation/authchecker/EmServiceAndUserDetails.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AnnotationSet.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Comment.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Rectangle.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/TagId.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/repository/EntityAuditEventRepository.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/MetaDataResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/CustomParameterizedException.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/BookmarkService.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/TagService.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/AnnotationDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/AnnotationSetDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/CommentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/RectangleDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/BookmarkServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/TagServiceImpl.java
Labels: ns:em, prd:em, rel:em-anno-pr-578

#579 EM-4044: fix checkstyle type error v5
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/util/PaginationUtil.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/AuditEventService.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/util/RandomUtil.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSetTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/util/PaginationUtilUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/MetadataServiceImplTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-579

#580 EM-4044: fix sonar major code smell
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/util/HeaderUtil.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-580

#559 EM-4015: upgrade spring boot 2.5.4
  build.gradle
  src/aat/resources/application.yml
Labels: ns:em, prd:em, rel:em-anno-pr-559

#593 EM-4061-SecurityScan Fix
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-593
