Repository hmcts/em-annotation-api, pull requests merged in 2021-02, with the labels that each got.

#336 Resolved vulnerability
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-336

#337 EM-3462 - EM-Anno api: Add functional test cases for CommentsResource
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java
Labels: ns:em, prd:em, rel:em-anno-pr-337

#338 EM-3462_2 - fix for jenkins build failures
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java
Labels: ns:em, prd:em, rel:em-anno-pr-338

#344 EM-3507 - EM-Anno api: Check & Update PACT/Jupiter Unit tests related…
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-344

#346 EM-3507 - EM-Anno api: Check & Update PACT/Jupiter Unit tests related…
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-346

#349 Resolved CVE-2021-21290
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-349

#350 EM-3524 - EM-Anno api: suppress security scan error
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-350

#348 Em 3507 - Updated build.gradle and resolved CVEs
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-348

#362 Updated terraform and gradle version
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/.terraform-version
Labels: ns:em, prd:em, rel:em-anno-pr-362
