Repository hmcts/em-annotation-api, pull requests merged in 2021-10, with the labels that each got.

#569 EM 3457 postgres upgrade v11
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-anno-pr-569

#597 Demo
  infrastructure/.terraform-version
  infrastructure/application-insights.tf
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:em, prd:em, rel:em-anno-pr-597

#601 Add InvalidTokenException to ServiceNameAspect and its test class
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspect.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspectTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-601

#602 security-scan-em-anno
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-602

#603 security-scan-em-anno
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-603

#604 Pointing to v11 DB details
  charts/em-anno/Chart.yaml
  charts/em-anno/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, rel:em-anno-pr-604

#605 EM-4073: remove jcenter reference
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
Labels: ns:em, prd:em, rel:em-anno-pr-605
