Repository hmcts/em-annotation-api, pull requests merged in 2022-07, with the labels that each got.

#835 added suppression for single fingerprint for em anno
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-835

#845 [EM-4494]-AnnotationAPI Security Scan fix
  audit.json
Labels: ns:em, prd:em, em-automation, rel:em-anno-pr-845

#849 Update README.md
  README.md
Labels: ns:em, prd:em, rel:em-anno-pr-849

#866 Removed redundant cve suppression
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-866
