Repository hmcts/em-annotation-api, pull requests merged in 2022-09, with the labels that each got.

#936 Added in dependabot config
  .github/dependabot.yml
  .github/renovate.json
  .github/stale.yml
  renovate.json
Labels: ns:em, prd:em, rel:em-anno-pr-936

#945 Revert "Bump flyway-core from 8.5.13 to 9.2.2"
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-945

#954 Use em-test-helper version 1.21.4
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-954

#955 EM-4227 copy app-insight connection from rpa
  charts/em-anno/Chart.yaml
  charts/em-anno/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-955

#959 revert "Merge pull request #949 from hmcts/dependabot/gradle/org.flywaydb-flyway-core-9.3.0"
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-959

#963 added suppression for 3 fingerprints for em anno
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-963

#967 added suppression for 4 fingerprints for em anno 20/09/2022
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-967

#970 5 fingerprints added for em anno 20/09/2022
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-970

#983 Fix response codes
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ErrorConstants.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java
Labels: ns:em, prd:em, rel:em-anno-pr-983
