Repository hmcts/em-annotation-api, pull requests merged in 2022-08, with the labels that each got.

#871 Updated DB core to 4 for Demo env
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-anno-pr-871

#872 Disable syncBranchesWithMaster till DB core is upgraded
  Jenkinsfile_CNP
Labels: ns:em, prd:em, rel:em-anno-pr-872

#873 Updated DB core from 2 to 4
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, rel:em-anno-pr-873

#880 Migration to flyway
  Jenkinsfile_CNP
  build.gradle
  charts/em-anno/Chart.yaml
  charts/em-anno/values.aat.template.yaml
  charts/em-anno/values.preview.template.yaml
  charts/em-anno/values.yaml
  gradle.properties
  gradle/liquibase.gradle
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/state.tf
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/data/migration/FlywayNoOpStrategy.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/data/migration/PendingMigrationScriptException.java
  src/main/resources/application.yaml
  src/main/resources/db/changelog/00000000000000_initial_schema.xml
  src/main/resources/db/changelog/20180917100756_added_entity_AnnotationSet.xml
  src/main/resources/db/changelog/20180917100757_added_entity_Annotation.xml
  src/main/resources/db/changelog/20180917100757_added_entity_constraints_Annotation.xml
  src/main/resources/db/changelog/20180917100757_added_entity_constraints_AnnotationSet.xml
  src/main/resources/db/changelog/20180917100758_added_entity_Comment.xml
  src/main/resources/db/changelog/20180917100758_added_entity_constraints_Comment.xml
  src/main/resources/db/changelog/20180917101255_added_entity_Rectangle.xml
  src/main/resources/db/changelog/20180917101255_added_entity_constraints_Rectangle.xml
  src/main/resources/db/changelog/20180917112342_added_entity_EntityAuditEvent.xml
  src/main/resources/db/changelog/20181005171348_changelog.xml
  src/main/resources/db/changelog/20200303154954_added_entity_Tag.xml
  src/main/resources/db/changelog/20200320123648_added_entity_Bookmark.xml
  src/main/resources/db/changelog/20200422103555_added_entity_constraints_Bookmark.xml
  src/main/resources/db/changelog/20200629224352_added_entity_Metadata.xml
  src/main/resources/db/db.changelog-master.xml
  src/main/resources/db/migration/V1__initial.sql
  src/main/resources/liquibase.properties
  src/test/resources/config/application.yaml
Labels: ns:em, prd:em, rel:em-anno-pr-880

#885 Migration to flyway on AAT & Prod
  build.gradle
  charts/em-anno/Chart.yaml
  charts/em-anno/values.aat.template.yaml
  charts/em-anno/values.preview.template.yaml
  charts/em-anno/values.yaml
  gradle.properties
  gradle/liquibase.gradle
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/FlywayConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/data/migration/FlywayNoOpStrategy.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/data/migration/PendingMigrationScriptException.java
  src/main/resources/application.yaml
  src/main/resources/db/changelog/00000000000000_initial_schema.xml
  src/main/resources/db/changelog/20180917100756_added_entity_AnnotationSet.xml
  src/main/resources/db/changelog/20180917100757_added_entity_Annotation.xml
  src/main/resources/db/changelog/20180917100757_added_entity_constraints_Annotation.xml
  src/main/resources/db/changelog/20180917100757_added_entity_constraints_AnnotationSet.xml
  src/main/resources/db/changelog/20180917100758_added_entity_Comment.xml
  src/main/resources/db/changelog/20180917100758_added_entity_constraints_Comment.xml
  src/main/resources/db/changelog/20180917101255_added_entity_Rectangle.xml
  src/main/resources/db/changelog/20180917101255_added_entity_constraints_Rectangle.xml
  src/main/resources/db/changelog/20180917112342_added_entity_EntityAuditEvent.xml
  src/main/resources/db/changelog/20181005171348_changelog.xml
  src/main/resources/db/changelog/20200303154954_added_entity_Tag.xml
  src/main/resources/db/changelog/20200320123648_added_entity_Bookmark.xml
  src/main/resources/db/changelog/20200422103555_added_entity_constraints_Bookmark.xml
  src/main/resources/db/changelog/20200629224352_added_entity_Metadata.xml
  src/main/resources/db/db.changelog-master.xml
  src/main/resources/db/migration/V1__baseline_migration.sql
  src/main/resources/liquibase.properties
  src/test/resources/config/application.yaml
Labels: ns:em, prd:em, rel:em-anno-pr-885

#891 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-891

#894 Fix metadata id attribute
  src/main/resources/db/migration/V1__baseline_migration.sql
Labels: ns:em, prd:em, rel:em-anno-pr-894

#899 Resolved service exception
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/ServiceNameAspect.java
Labels: ns:em, prd:em, rel:em-anno-pr-899

#900 Resolved fortify issue
  dependency-check-suppressions.xml
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  docker-compose.yml
  docker-pactbroker-compose.yml
Labels: ns:em, prd:em, rel:em-anno-pr-900

#904 Resolve preview secret issue
  charts/em-anno/Chart.yaml
  charts/em-anno/values.preview.template.yaml
  charts/em-anno/values.yaml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-anno-pr-904

#907 Increased DB storage size for Perftest & Prod
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-907
