Repository hmcts/em-annotation-api, pull requests merged in 2022-06, with the labels that each got.

#787 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-787

#780 Removed redundant classes
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/EmailAlreadyUsedException.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/EmailNotFoundException.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/InternalServerErrorException.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/InvalidPasswordException.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/LoginAlreadyUsedException.java
Labels: ns:em, prd:em, rel:em-anno-pr-780

#782 Em 3592 code coverage securityutils
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtils.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityUtilsTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-782

#784 Em 3593 code coverage entityauditeventlistener
  src/test/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListenerTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-784

#796 added suppressions into audit.json to fix nightly pipeline.
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-796

#797 added further suppressions into audit.json to fix nightly pipeline.
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-797

#794 Add cftlib
  README.md
  build.gradle
  docker-compose-dependencies-db.yml
  settings.gradle
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-anno-pr-794

#802 Updated local S2S port and Idam port
  bin/idam/idam.sh
  bin/start-local-environment.sh
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
Labels: ns:em, prd:em, rel:em-anno-pr-802

#807 Updated local DB port and details
  docker-compose-dependencies-db.yml
  docker-compose-dependencies-simulator.yml
  docker-compose-dependencies.yml
  gradle/liquibase.gradle
  src/main/resources/liquibase.properties
Labels: ns:em, prd:em, rel:em-anno-pr-807

#809 Resolved integration test failures
  src/test/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSetTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TagResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/service/impl/IdamDetailsFilterServiceImplIntTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-809

#825 added further suppression's for em anno
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-825
