Repository hmcts/em-annotation-api, pull requests merged in 2022-03, with the labels that each got.

#694 [EM-4287]-Security Scan Fix
  audit.json
Labels: ns:em, prd:em, em-automation, rel:em-anno-pr-694

#696 bump java chart
  charts/em-anno/Chart.yaml
Labels: ns:em, prd:em, rel:em-anno-pr-696

#701 Updated column name to resolve reserve word issue
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/PersistentAuditEvent.java
  src/main/resources/db/changelog/00000000000000_initial_schema.xml
Labels: ns:em, prd:em, rel:em-anno-pr-701

#702 Resolved local setup port issue
  bin/start-local-environment.sh
  docker-compose-dependencies.yml
  src/aat/resources/application.yml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-anno-pr-702

#695 Updated SpringBoot version to 2.6.4
  build.gradle
  src/main/java/uk/gov/hmcts/reform/em/annotation/Application.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/SwaggerConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/MetaDataResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/TagResource.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepositoryIntTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-695

#708 security fix -swagger url changed to v3
  security.sh
Labels: ns:em, prd:em, rel:em-anno-pr-708

#715 added: jackson-databind version to manually be set to 2.13.2.1.
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-715

#718 Remove jackson-bom
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-718

#720 Updated azurerm version
  infrastructure/state.tf
Labels: ns:em, prd:em, rel:em-anno-pr-720

#721 [EM-4356]-SecurityScan Fix
  audit.json
Labels: ns:em, prd:em, em-automation, rel:em-anno-pr-721
