Repository hmcts/em-annotation-api, pull requests merged in 2023-10, with the labels that each got.

#1550 Suppress CVE-2023-4586
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1550

#1573 EM-5505 reduce app-insight logs
  lib/applicationinsights.json
Labels: ns:em, prd:em, rel:em-anno-pr-1573

#1580 Added in v15 DB details for perftest
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1580
