Repository hmcts/em-annotation-api, pull requests merged in 2023-01, with the labels that each got.

#1119 EM-4912-suppress-vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1119

#1113 EM-4479: Returning all bookmarks
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java
Labels: ns:em, prd:em, rel:em-anno-pr-1113

#1129 EM-4939 - added 6 fingerprints to audit.json to fix em anno pipeline
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1129

#1132 Suppress CVE
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1132

#1134 EM-4942 - added 1 fingerprint to audit.json to fix em anno pipeline
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1134

#1133 EM-4942 - added 1 fingerprint to audit.json to fix em anno pipeline
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1133

#1135 EM-4943 suppress vulnerability
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1135

#1140 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1140

#1167 EM-5015-bump-hmcts.java
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1167

#1173 EM-5019 fix pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:em, prd:em, rel:em-anno-pr-1173
