Repository hmcts/em-annotation-api, pull requests merged in 2023-09, with the labels that each got.

#1474 Resolve CVE-2023-41080
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1474

#1492 Update Renovate config
  .github/renovate.json
Labels: ns:em, prd:em, rel:em-anno-pr-1492

#1518 Em 5551 update renovate config
  .github/dependabot.yml
  .github/stale.yml
Labels: ns:em, prd:em, rel:em-anno-pr-1518

#1520 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1520

#1523 Em 5551 update renovate config
  .github/renovate.json
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1523

#1531 EM-5569 dependency-check-suppressions.xml
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1531
