Repository hmcts/em-annotation-api, pull requests merged in 2023-05, with the labels that each got.

#1306 EM-5230 avoid CVE-2023-20862
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1306

#1312 Refer to new AppInsights details
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1312

#1315 Removed unused appinsights file
  infrastructure/application-insights.tf
Labels: ns:em, prd:em, destroy, rel:em-anno-pr-1315

#1337 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:em, prd:em, rel:em-anno-pr-1337
