Repository hmcts/em-annotation-api, pull requests merged in 2023-07, with the labels that each got.

#1388 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1388

#1352 Upgraded spring boot
  build.gradle
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/AnnotationSetScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/CommentScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/FilterAnnotationSetScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/MetadataScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/OpenIdConnectScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/RectangleScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/TagScenarios.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/smoke/SmokeTest.java
  src/aat/java/uk/gov/hmcts/reform/em/annotation/testutil/TestUtil.java
  src/aat/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/em/annotation/Application.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/JacksonConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListener.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AbstractAuditingEntity.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Annotation.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/AnnotationSet.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Bookmark.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Comment.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/EntityAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/IdamDetails.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Metadata.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/PersistentAuditEvent.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Rectangle.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/domain/Tag.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/EmErrorController.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSet.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResource.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslator.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/BookmarkService.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/BookmarkDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/CommentDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/MetadataDto.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/dto/TagDTO.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/AnnotationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/service/impl/BookmarkServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/em/annotation/config/audit/EntityAuditEventListenerTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/config/security/JwtGrantedAuthoritiesConverterTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/config/security/SecurityConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/repository/CustomAuditEventRepositoryIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/AnnotationSetResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/CommentResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/EmErrorControllerIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/FilterAnnotationSetTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/RectangleResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TagResourceIntTest.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/TestSecurityConfiguration.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/errors/ExceptionTranslatorTestController.java
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1352

#1395 Upgraded gradle version to 8
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:em, prd:em, rel:em-anno-pr-1395

#1406 Reverted serenity & pact lib versions
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1406

#1414 Updated Hikari connection-timeout
  charts/em-anno/Chart.yaml
  charts/em-anno/values.yaml
  src/main/resources/application.yaml
Labels: ns:em, prd:em, Do Not Merge, rel:em-anno-pr-1414

#1421 respond with 204
  src/aat/java/uk/gov/hmcts/reform/em/annotation/functional/BookmarkScenarios.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResource.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/BookmarkResourceIntTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-1421

#1430 upgrade spring boot to 3.1.2
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1430

#1436 Resolved CVE & removed redundant CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1436

#1432 em-5435: added 4 fingerprints to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1432
