Repository hmcts/em-annotation-api, pull requests merged in 2023-12, with the labels that each got.

#1646 em-5710: added 1 fingerprint to audit.json
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1646

#1635 Update v15 Prod DB config
  build.gradle
  infrastructure/prod.tfvars
Labels: ns:em, prd:em, add-or-update, Do Not Merge, rel:em-anno-pr-1635

#1636 Update v15 DB config to rewrite access roles
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, destroy, rel:em-anno-pr-1636

#1661 Update v15 db config after migration
  charts/em-anno/Chart.yaml
  charts/em-anno/values.yaml
  infrastructure/main.tf
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1661

#1671 EM-5717 arrange dependency management
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1671

#1670 Removed v11 DB related config
  infrastructure/main.tf
  infrastructure/perftest.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:em, prd:em, destroy, rel:em-anno-pr-1670
