Repository hmcts/em-annotation-api, pull requests merged in 2023-04, with the labels that each got.

#1268 Updated CVE list
  build.gradle
  config/owasp/dependency-check-suppressions.xml
Labels: ns:em, prd:em, rel:em-anno-pr-1268

#1283 Em-5186 suppress sec scan vulnerability
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1283

#1288 Preview dependency chart update
  charts/em-anno/Chart.yaml
  charts/em-anno/values.preview.template.yaml
  charts/em-anno/values.yaml
Labels: ns:em, prd:em, add-or-update, rel:em-anno-pr-1288

#1289 EM-5198 security scan
  audit.json
  functional-output/zap.reports
Labels: ns:em, prd:em, rel:em-anno-pr-1289

#1292 Welcome Endpoint to return Json format
  src/aat/java/uk/gov/hmcts/reform/em/annotation/smoke/SmokeTest.java
  src/main/java/uk/gov/hmcts/reform/em/annotation/rest/WelcomeResource.java
  src/test/java/uk/gov/hmcts/reform/em/annotation/rest/WelcomeResourceTest.java
Labels: ns:em, prd:em, rel:em-anno-pr-1292

#1291 EM-5198 suppress sec vul
  audit.json
Labels: ns:em, prd:em, rel:em-anno-pr-1291

#1297 Resolved CVE
  build.gradle
Labels: ns:em, prd:em, rel:em-anno-pr-1297
